---
language: c

before_install:
  - echo 'deb http://repos.moxielogic.org:7114/MoxieLogic moxiedev main' | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y --allow-unauthenticated moxielogic-moxie-elf-gcc moxielogic-moxie-elf-gdb-sim dejagnu

script:
  - /opt/moxielogic/bin/moxie-elf-gcc -v
  - echo ----------------------------------
  - echo $HOME
  - echo ----------------------------------
  - pwd
  - echo ----------------------------------
  


