---
sudo: required

language: c

services:
  - docker

before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register
  - docker pull multiarch/debian-debootstrap:armhf-jessie

script:
  - docker run -it --rm multiarch/debian-debootstrap:armhf-jessie uname -a
  


