---
language: c

before_install:
  - sudo apt-add-repository http://repos.moxielogic.org:7114/MoxieLogic -y
  - sudo apt-get update -q
  - sudo apt-get install -y moxielogic-moxie-elf-gcc moxielogic-moxie-elf-sim

script:
  - /opt/moxielogic/bin/moxie-elf-gcc -v


